name: Build and Deploy JAR app to Azure Web App

on:
  push:
    branches:
      - main  # Tên nhánh Git mà bạn muốn theo dõi, có thể thay thế bằng nhánh khác nếu cần

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ecowhelssping'  # Thay bằng tên Azure Web App của bạn
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        package: '*.jar'
